# Generated by Django 5.1.3 on 2024-11-13 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(max_length=200)),
                ('added_by', models.CharField(max_length=100)),
                ('student_cls', models.IntegerField()),
                ('division', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to='notes/')),
                ('status', models.CharField(default='active', max_length=20)),
            ],
            options={
                'db_table': 'notes',
            },
        ),
    ]
