# Generated by Django 5.1.3 on 2024-11-13 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='division',
        ),
    ]
