# Generated by Django 5.1.3 on 2024-11-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.IntegerField()),
                ('teacher_name', models.CharField(max_length=50)),
                ('teacher_class', models.IntegerField()),
                ('division', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=30)),
                ('section', models.CharField(max_length=30)),
                ('staff_status', models.CharField(default='active', max_length=20)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
