# Generated by Django 5.1.3 on 2024-11-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('admission_no', models.IntegerField()),
                ('student_name', models.CharField(max_length=50)),
                ('student_class', models.IntegerField()),
                ('division', models.CharField(max_length=10)),
                ('student_status', models.CharField(default='active', max_length=20)),
                ('status', models.CharField(default='active', max_length=20)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
