# Generated by Django 5.1.3 on 2024-11-13 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_teacher', '0003_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
    ]
